swagger: "2.0"
info:
  title: "New Beginings"
  version: 1.0.0
tags:
  - name: Users
schemes:
- "https"
definitions:
  Users:
    type: array
    items:
      $ref : "#/definitions/User"
  User:
    type: object
    properties:
        user_id:
          type : "string"
          description : " user reference id"
        username:
          type: "string"
          description: " user name "
        dob:
          type: "string"
          description: "date of birth"
        phone_number:
          type: string
          description : "user phone number"
        address:
          type: string
          description: "address"

  ErrorMessage:
    type : object
    properties:
      status_code :
        type: number
        description: status codes 401 , 500 , 403 , 413, 409
      error_message:
        type : string
        description : error message
paths:
  /api/v1/users/{id}:
    get:
      description: Get user data
      summary : Get user
      consumes:
        - applicaiton/json
      produces:
        - application/json
      parameters:
        - name : id
          in : path
          type : string
          required : true
          description : user reference number
      responses:
        200:
          description: Successful response
          schema:
            $ref : "#/definitions/User"
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorMessage"
        413:
          description: Request-size limit exceeded
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
    put:
      description: update user data
      summary: update user data
      consumes:
        - applicaiton/json
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: user reference number
        - name : user
          in: body
          description: user name
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Successfully updated
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorMessage"
        413:
          description: Request-size limit exceeded
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
    delete:
      description: delete user
      summary: delete user
      consumes:
        - applicaiton/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: user reference number
      responses:
        200:
          description: Deleted Successfully
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorMessage"
        413:
          description: Request-size limit exceeded
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
  /api/v1/users:
    post:
      description: Create user
      summary: Create new user
      consumes:
        - application/json
      parameters:
        - in : body
          name : user
          description : user name
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorMessage"
        413:
          description: Request-size limit exceeded
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
    get:
      description: Get all users based on the query params
      summary: Get users
      consumes:
        - applicaiton/json
      produces:
        - application/json
      parameters:
        - name: username
          in: query
          type: string
          required: false
          description: username
        - name: limit
          in: query
          type: integer
          default: 50
          required: false
        - name: offset
          in: query
          type: integer
          default: 0
          required: false
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Users"
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorMessage"
        413:
          description: Request-size limit exceeded
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
